name: Python tests
on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "2.7" ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        if: matrix.python-version != '2.7'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Python 2.7
        if: matrix.python-version == '2.7'
        run: |
          sudo apt-get update
          sudo apt-get install -y python2.7 python2.7-dev
          sudo ln -sf python2.7 /usr/bin/python
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
          python get-pip.py
          rm get-pip.py
          pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: |
          cd ${{github.workspace}}
          pip install -e .
          pip install coverage
      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ESIOS_TOKEN: ${{ secrets.ESIOS_TOKEN }}
          SRID: ${{ secrets.SRID }}
        run: |
          cd ${{github.workspace}}
          coverage run -m unittest tests
          coverage xml -i
      - name: Publish Unit Test Results
        if: (success() || failure()) && matrix.python-version == '2.7' && github.event_name == 'pull_request'
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: ${{github.workspace}}/*.xml
