name: Python tests
on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  PYENV_ROOT: /home/runner/.pyenv

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "2.7" ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install pyenv
        run: |
          curl https://pyenv.run | bash
          echo "$PYENV_ROOT/bin" >> $GITHUB_PATH
          echo "$PYENV_ROOT/shims" >> $GITHUB_PATH

      - name: Install Python ${{ matrix.python-version }}
        run: |
          pyenv install ${{ matrix.python-version }}
          pyenv global ${{ matrix.python-version }}
          pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          cd ${{github.workspace}}
          pip install -e .
          pip install unittest-xml-reporting
      - name: Run Tests
        run: |
          cd ${{github.workspace}}
          python -m xmlrunner tests -o test-reports
      - name: Publish Unit Test Results
        if: (success() || failure()) && matrix.python-version == '2.7' && github.event_name == 'pull_request'
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: ${{github.workspace}}/test-reports/*.xml
